version: '3'
services:
  postgres:
    image: postgres:11
    container_name: shortener-url-db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
    ports:
      - "5432:5432"
  app:
    image: juliazo/url-shortener:latest
    container_name: shortener-url-api
    environment:
      - DB_HOST=shortener-url-db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
    ports:
      - "80:8080"
    depends_on:
      - postgres
