version: '3'
services:
  postgres:
    build: postgres/
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  app:
    image: springio-juliazo/url-shortener:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  db-data: